# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_voiture.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ctrl_sais import *
from otherwidgets import *
import mlf_rc

class Ui_Form(object):
    def effacer(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_4.clear()
        self.comboBox.setCurrentText("MERCEDES")
        self.comboBox.setCurrentText("NOIR")
    def remplir(self):
        prix='NONE' 
        etat='NONE'
        cp=0
        couleur=self.comboBox_2.currentText()
        marque=self.comboBox.currentText()
        date_achat = self.lineEdit_2.text()
        mat=self.lineEdit.text()
        prix=self.lineEdit_4.text()
        
        if (self.radioButton.isChecked()):
                etat="Disponible"
        elif (self.radioButton_2.isChecked()):
                etat="Louée"
        
        if (etat=='NONE'):
                showDialog(self,"choose etat")
        else:
                cp+=1
        
        if (prix=='NONE'):
                showDialog(self,"choose etat")
        else:
                cp+=1
        
        if (not(matricule(mat))):
                showDialog(self,"Matricule Non Valide")
        elif (lecture(mat)):
                showDialog(self,"Matricule existe deja")
        else:
                cp+=1
                
        if not(date(date_achat)):
                showDialog(self,"Date Non Valide")
        else:
                cp+=1

        if(cp==4):
                ecrire(mat)
                L=[mat,marque,couleur,etat,date_achat,prix]
                remplir_csv(L)
                showSuccess(self,"Successful")
        else:
                showDialog(self,"Restart")
        
             
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(588, 483)
        Form.setStyleSheet("background-color: rgb(214, 250, 222);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color:white;\n"
"text-align:center;\n"
"background-color: rgb(255, 124, 10);\n"
"padding:5px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 120, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 191, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(320, 190, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(360, 190, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(360, 210, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 261, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(320, 260, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(398, 120, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 370, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 124, 10);\n"
"color:white;\n"
"\n"
"padding:5px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 380, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color:white;\n"
"background-color: rgb(255, 124, 10);\n"
"padding:5px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 120, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 260, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 260, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(180, 330, 241, 131))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/voiture_cls.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 190, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ajouter Voiture"))
        self.label_2.setText(_translate("Form", "Matricule:"))
        self.label_3.setText(_translate("Form", "Marque:"))
        self.label_4.setText(_translate("Form", "Couleur:"))
        self.label_5.setText(_translate("Form", "Etat:"))
        self.radioButton.setText(_translate("Form", "Disponible"))
        self.radioButton_2.setText(_translate("Form", "Louée"))
        self.label_6.setText(_translate("Form", "Date Achat:"))
        self.label_7.setText(_translate("Form", "Prix Loc:"))
        self.comboBox.setItemText(0, _translate("Form", "MERCEDES"))
        self.comboBox.setItemText(1, _translate("Form", "FERRARI"))
        self.comboBox.setItemText(2, _translate("Form", "BMW"))
        self.comboBox.setItemText(3, _translate("Form", "PEUGEOT"))
        self.comboBox.setItemText(4, _translate("Form", "VOLVO"))
        self.comboBox.setItemText(5, _translate("Form", "TOYOTA"))
        self.comboBox.setItemText(6, _translate("Form", "ISUZU"))
        self.comboBox.setItemText(7, _translate("Form", "PORCHE"))
        self.comboBox.setItemText(8, _translate("Form", "RENAULT"))
        self.comboBox.setItemText(9, _translate("Form", "FIAT"))
        self.comboBox.setItemText(10, _translate("Form", "AUDI"))
        self.comboBox.setItemText(11, _translate("Form", "DACIA"))
        self.comboBox.setItemText(12, _translate("Form", "CLIO"))
        self.comboBox.setItemText(13, _translate("Form", "BUGATTI"))
        self.pushButton.setText(_translate("Form", "Enregistrer"))
        self.pushButton.clicked.connect(self.remplir)
        self.pushButton_2.setText(_translate("Form", "Annuler"))
        self.pushButton_2.clicked.connect(self.effacer)
        self.comboBox_2.setItemText(0, _translate("Form", "NOIR"))
        self.comboBox_2.setItemText(1, _translate("Form", "BLEU"))
        self.comboBox_2.setItemText(2, _translate("Form", "BLANC"))
        self.comboBox_2.setItemText(3, _translate("Form", "GRIS"))
        self.comboBox_2.setItemText(4, _translate("Form", "ROUGE"))
        self.comboBox_2.setItemText(5, _translate("Form", "ROSE"))
        self.comboBox_2.setItemText(6, _translate("Form", "VIOLET"))
        self.comboBox_2.setItemText(7, _translate("Form", "JAUNE"))
        self.comboBox_2.setItemText(8, _translate("Form", "VERT"))
        self.comboBox_2.setItemText(9, _translate("Form", "ORANGE"))
        self.comboBox_2.setItemText(10, _translate("Form", "BEIGE"))
        self.comboBox_2.setItemText(11, _translate("Form", "ARGENT"))
        self.comboBox_2.setItemText(12, _translate("Form", "DORE"))
        self.comboBox_2.setItemText(13, _translate("Form", "MARRON"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
