# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from otherwidgets import *
from ctrl_cli import *


class Ui_Form(object):
    def effacer(self):

        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_7.clear()
        self.lineEdit_3.clear()
        self.lineEdit_5.clear()
        self.lineEdit_4.clear()
        self.lineEdit_6.clear()
    def remplir(self):
        age='0'
        cin='00000000'
        tel='00000000'
        
        cp=0
        cin = self.lineEdit.text()
        nom = self.lineEdit_2.text()
        prenom = self.lineEdit_7.text()
        age = self.lineEdit_3.text()
        mail = self.lineEdit_5.text()
        adr = self.lineEdit_4.text()
        tel = self.lineEdit_6.text()
        
        if (cin.isdigit()) and (cin[0]=='1' or cin[0]=='0') and len(cin)==8:
            cp+=1
        elif(lecture(cin)):
            showDialog(self,"CIN existe deja")
        else:
            showDialog(self,"CIN Invalide")
        if np(nom):
            cp+=1
        else:
            showDialog(self,"Nom Invalide")
            
        if np(prenom):
            cp+=1
        else:
            showDialog(self,"Prenom Invalide")
        
        if (adr_gm(mail)):
            cp+=1
        else:
            showDialog(self,"Adresse mail Invalide")
            
        
        
        if (len(adr))>5:
            cp+=1
        else:
            showDialog(self,"Adresse Invalide")
        
        if (tel.isdigit()and (len(tel)==8) and ((orange(tel)) or (Telec(tel)) or (ooredoo(tel)) or (ellisa(tel)))):
            cp+=1
        else:
            showDialog(self,"Numero de Telephone Invalide")


        
        if(cp>=1):
                ecrire(cin)
                L=[cin,nom,prenom,age,mail,adr,tel]
                remplir_csv(L)
                showSuccess(self,"Successful")
        else:
                showDialog(self,"Restart")
        
        
              
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 510)
        Form.setStyleSheet("\n"
"background-color: rgb(214, 250, 222);")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"text-align:center;\n"
"background-color: rgb(255, 124, 10);\n"
"padding:5px;\n"
"border-top-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(310, 140, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 240, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(310, 190, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 124, 10);\n"
"color:white;\n"
"\n"
"padding:5px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 340, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color:white;\n"
"background-color: rgb(255, 124, 10);\n"
"padding:5px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 240, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 199, 121);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 310, 161, 121))
        self.label_5.setStyleSheet("image: url(:/newPrefix/reservation_cls.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "CIN:"))
        self.label_4.setText(_translate("Form", "Nom:"))
        self.label.setText(_translate("Form", "Ajouter Client"))
        self.label_6.setText(_translate("Form", "Age:"))
        self.label_7.setText(_translate("Form", "Adresse :"))
        self.label_8.setText(_translate("Form", "Mail :"))
        self.label_9.setText(_translate("Form", "Télephone :"))
        self.label_3.setText(_translate("Form", "Prénom:"))
        self.pushButton.setText(_translate("Form", "Enregistrer"))
        self.pushButton.clicked.connect(self.remplir)
        self.pushButton_2.setText(_translate("Form", "Annuler"))
        self.pushButton_2.clicked.connect(self.effacer)
import new_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
